### ISSUE TITLE
batch limitation

### ISSUE THREAD

**Issue by alannssantos** [SuarthaGautama/mangascandl#2]
`$ mangascandl batch https://mangadex.org/title/286/ 1 4 'Fullmetal Alchemist Vol.01'`

```
Traceback (most recent call last):
  File "/home/alann/.local/bin/mangascandl", line 10, in <module>
    sys.exit(main())
  File "/home/alann/.local/lib/python3.7/site-packages/mangascandl/mangascandl.py", line 46, in main
    extractor.download_batch(opts.url,opts.starting_chapter,opts.end_chapter,opts.destination_folder)
  File "/home/alann/.local/lib/python3.7/site-packages/mangascandl/extractor/common.py", line 108, in download_batch
    chapter_url_list = self.get_chapter_url_to_download(title_url,start,end)
  File "/home/alann/.local/lib/python3.7/site-packages/mangascandl/extractor/Mangadex.py", line 85, in get_chapter_url_to_download
    chapter_index = float(chapter_info['chapter'])
ValueError: could not convert string to float:
```

**Comment by alannssantos** [comment]
When the value of the chapter is empty this error appear.
```
{'volume': '0', 'chapter': '', 'title': 'Oneshot - Прототип (SPOILERS!)', 'lang_name': 'Russian', 'lang_code': 'ru', 'group_id': 657, 'group_name': 'no group', 'group_id_2': 0, 'group_name_2': None, 'group_id_3': 0, 'group_name_3': None, 'timestamp': 1551788278, 'comments': None}
```
